add_subdirectory(assetc)
add_subdirectory(assetdbprobe)
add_subdirectory(packageprobe)
add_subdirectory(vfsprobe)
add_subdirectory(streamingprobe)
add_subdirectory(worldpartitionprobe)
add_subdirectory(worldtopologyprobe)
add_subdirectory(gravityprobe)
add_subdirectory(terrainprobe)
add_subdirectory(ntcprobe)
add_subdirectory(splineprobe)
add_subdirectory(csgprobe)
add_subdirectory(physicsprobe)
add_subdirectory(characterprobe)
add_subdirectory(vehicleprobe)
add_subdirectory(ragdollprobe)
add_subdirectory(softbodyprobe)
add_subdirectory(fluidprobe)
add_subdirectory(settingsprobe)
add_subdirectory(serializationprobe)
add_subdirectory(mathprobe)
add_subdirectory(geomprobe)
add_subdirectory(ecsprobe)
add_subdirectory(worldprobe)
add_subdirectory(invariantprobe)
add_subdirectory(clockprobe)
add_subdirectory(transformprobe)
add_subdirectory(boundsprobe)
add_subdirectory(resourceprobe)
add_subdirectory(memoryprobe)
add_subdirectory(diagnosticsprobe)
add_subdirectory(renderprobe)
add_subdirectory(rhiprobe)
add_subdirectory(integrationprobe)
add_subdirectory(vulkanprobe)
add_subdirectory(vulkanmeshprobe)
add_subdirectory(meshoptprobe)
add_subdirectory(vulkanuploadprobe)
add_subdirectory(vulkandrawprobe)
add_subdirectory(vulkanarchprobe)
add_subdirectory(vulkanframegraphprobe)
add_subdirectory(vulkanexecprobe)
add_subdirectory(pointcloudprobe)
add_subdirectory(pointcloudcookprobe)
add_subdirectory(pointcloudruntimeprobe)
add_subdirectory(editoruiprobe)
add_subdirectory(editorruntimeprobe)
add_subdirectory(editorpanelprobe)
add_subdirectory(editorinteractionprobe)
add_subdirectory(editorshellprobe)
add_subdirectory(editorwidgetprobe)
add_subdirectory(editoruxprobe)
add_subdirectory(editoruxruntimeprobe)
add_subdirectory(editortextprobe)
add_subdirectory(editorscrollprobe)
add_subdirectory(editorfocusprobe)
add_subdirectory(editordragdropprobe)
add_subdirectory(editorpropertyprobe)
add_subdirectory(editorcommandstateprobe)
add_subdirectory(editorthemeprobe)
add_subdirectory(editorlayoutprobe)
add_subdirectory(editorsessionprobe)
add_subdirectory(editorshortcutprobe)
add_subdirectory(editorpreferencesprobe)
add_subdirectory(editorworkspaceprobe)
add_subdirectory(editorautosaveprobe)
add_subdirectory(editoractivityprobe)
add_subdirectory(editordiagnosticspanelprobe)
add_subdirectory(editordiagnosticsviewprobe)
add_subdirectory(editordiagnosticsinteractionprobe)
add_subdirectory(editorcommandpaletteprobe)
add_subdirectory(editorcommandpaletteruntimeprobe)
add_subdirectory(editormenutoolbarprobe)
add_subdirectory(editortransformgizmoprobe)
add_subdirectory(editorsceneviewprobe)
add_subdirectory(inputprobe)
add_subdirectory(commandprobe)
add_subdirectory(jobprobe)
add_subdirectory(filesystemprobe)
add_subdirectory(policyprobe)
add_subdirectory(destructionprobe)
add_subdirectory(remeshprobe)
add_subdirectory(surfaceprobe)
add_subdirectory(projectileprobe)
add_subdirectory(debrisprobe)
add_subdirectory(damageprobe)
add_subdirectory(explosionprobe)
add_subdirectory(forcefieldprobe)
add_subdirectory(debugdrawprobe)
add_subdirectory(physicstelemetryprobe)
